version: '2.2'

networks:
  kong-edu-net:
    name: kong-edu-net
    driver: bridge

services:
  # keycloak:
  #   networks:
  #   - kong-edu-net
  #   image: jboss/keycloak:16.1.1
  #   container_name: keycloak
  #   hostname: keycloak
  #   command: -Dkeycloak.profile.feature.upload_scripts=enabled
  #   volumes:
  #   - /home/ubuntu/misc:/data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://keycloak:8080/auth/realms/master"]
  #     # test: ["CMD", "curl", "-f", "http://keycloak/auth/realms/master"]
  #     # test: ["CMD", "curl", "-f", "$KEYCLOAK_URI/auth/realms/master"]
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3
  #   restart: on-failure
  #   ports:
  #   - 8080:8080
  #   environment:
  #     DB_VENDOR: H2
  #     KEYCLOAK_USER: admin
  #     KEYCLOAK_PASSWORD: admin
  #     KEYCLOAK_IMPORT: "/data/kong_realm_template.json"
  #     PROXY_ADDRESS_FORWARDING: "true"

  postgres:
    networks:
    - kong-edu-net
    image: postgres:13.1
    container_name: postgres
    hostname: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    stdin_open: true
    tty: true
    environment:
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong

  kong-migrations:
    networks:
    - kong-edu-net
    image: kong/kong-gateway:3.1
    # image: kong/kong-gateway:2.8-alpine
    container_name: kong-migrations
    depends_on:
    - postgres
    command: kong migrations bootstrap
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: password
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}

  kong-migrations-up:
    networks:
    - kong-edu-net
    image: kong/kong-gateway:3.1
    # image: kong/kong-gateway:2.8-alpine
    container_name: kong-migrations-up
    depends_on:
    - kong-migrations
    command: kong migrations up && kong-migrations finish
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PASSWORD: password
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}

  kong-cp:
    networks:
    - kong-edu-net
    image: kong/kong-gateway:3.1
    # image: kong/kong-gateway:2.8-alpine
    container_name: kong-cp
    hostname: kong-cp
    user: kong
    depends_on:
    - kong-migrations-up
    volumes:
    - ${PWD}/ssl-certs:/srv/shared/ssl
    - ${PWD}/logs:/srv/shared/logs
    # - /usr/local/kong/logs:/srv/shared/logs
    # - /home/ubuntu/kong-gateway-operations/installation/ssl-certs:/srv/shared/ssl
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    ports:
    - "8001-8006:8001-8006/tcp"
    - "8100:8100/tcp"
    - "8444-8447:8444-8447/tcp"
    environment:
      KONG_ROLE: control_plane
      KONG_CLUSTER_CERT: /srv/shared/ssl/hybrid/cluster.crt
      KONG_CLUSTER_CERT_KEY: /srv/shared/ssl/hybrid/cluster.key
      KONG_CLUSTER_DATA_PLANE_PURGE_DELAY: 600
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 http2 ssl"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002, 0.0.0.0:8445 http2 ssl"
      KONG_PORTAL_GUI_LISTEN: "0.0.0.0:8003, 0.0.0.0:8446 http2 ssl"
      KONG_PORTAL_API_LISTEN: "0.0.0.0:8004, 0.0.0.0:8447 http2 ssl"
      KONG_STATUS_LISTEN: "0.0.0.0:8100"
      KONG_CLUSTER_LISTEN: "0.0.0.0:8005"
      KONG_CLUSTER_TELEMETRY_LISTEN: "0.0.0.0:8006"
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_MAX_CONCURRENT_QUERIES: 5
      KONG_ADMIN_ACCESS_LOG: /srv/shared/logs/admin_access.log
      KONG_ADMIN_ERROR_LOG: /srv/shared/logs/admin_error.log
      KONG_ADMIN_GUI_ACCESS_LOG: /srv/shared/logs/admingui_access.log
      KONG_ADMIN_GUI_ERROR_LOG: /srv/shared/logs/admingui_error.log
      KONG_PORTAL_API_ACCESS_LOG: /srv/shared/logs/portalapi_access.log
      KONG_PORTAL_API_ERROR_LOG: /srv/shared/logs/portalapi_error.log
      KONG_PORTAL_GUI_ACCESS_LOG: /srv/shared/logs/portalgui_access.log
      KONG_PORTAL_GUI_ERROR_LOG: /srv/shared/logs/portalgui_error.log
      KONG_STATUS_ACCESS_LOG: /srv/shared/logs/status_access.log
      KONG_STATUS_ERROR_LOG: /srv/shared/logs/status_error.log
      KONG_AUDIT_LOG: "on"
      KONG_STATUS_SSL_CERT_KEY: "/srv/shared/ssl/wildcard.key"
      KONG_STATUS_SSL_CERT: "/srv/shared/ssl/wildcard.pem"
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_VITALS: "on"
      KONG_VITALS_STRATEGY: prometheus
      KONG_VITALS_STATSD_ADDRESS: statsd:9125
      KONG_VITALS_TSDB_ADDRESS: prometheus:9090
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
     #KONG_ENFORCE_RBAC: "on"
     #KONG_ADMIN_API_URI: "https://api.kong.lan:8444"
      # KONG_ADMIN_API_URI: ${KONG_ADMIN_API_URI:-http://localhost:8001}
      KONG_ADMIN_API_URI: ${KONG_ADMIN_API_URI:-http://localhost:8001}
      KONG_ADMIN_SSL_CERT_KEY: "/srv/shared/ssl/wildcard.key"
      KONG_ADMIN_SSL_CERT: "/srv/shared/ssl/wildcard.pem"
     #KONG_ADMIN_GUI_URL: "https://manager.kong.lan:8445"
      KONG_ADMIN_GUI_URL: ${KONG_ADMIN_GUI_URL:-http://localhost:8002}
      KONG_ADMIN_GUI_SSL_CERT_KEY: "/srv/shared/ssl/wildcard.key"
      KONG_ADMIN_GUI_SSL_CERT: "/srv/shared/ssl/wildcard.pem"
     #KONG_ADMIN_GUI_AUTH: "basic-auth"
     #KONG_ADMIN_GUI_SESSION_CONF: "{ \"cookie_name\": \"manager-session\", \"secret\": \"this_is_my_other_secret\", \"storage\": \"kong\", \"cookie_secure\":true, \"cookie_lifetime\":36000}"
      KONG_PORTAL: "on"
      KONG_PORTAL_GUI_PROTOCOL: "http"
      # KONG_PORTAL_GUI_PROTOCOL: "https"
     #KONG_PORTAL_GUI_HOST: "portal.kong.lan:8446"
      KONG_PORTAL_GUI_HOST: ${KONG_PORTAL_GUI_HOST:-localhost:8003}
      KONG_PORTAL_GUI_SSL_CERT_KEY: "/srv/shared/ssl/wildcard.key"
      KONG_PORTAL_GUI_SSL_CERT: "/srv/shared/ssl/wildcard.pem"
     #KONG_PORTAL_API_URL: "https://portal-api.kong.lan:8447"
      KONG_PORTAL_API_URL: ${KONG_PORTAL_API_URL:-http://localhost:8004}
      KONG_PORTAL_API_SSL_CERT_KEY: "/srv/shared/ssl/wildcard.key"
      KONG_PORTAL_API_SSL_CERT: "/srv/shared/ssl/wildcard.pem"
      KONG_PORTAL_AUTH: "basic-auth"
      KONG_PORTAL_SESSION_CONF: "{\"cookie_name\":\"portal-session\",\"secret\":\"this_is_my_secret\",\"storage\":\"kong\",\"cookie_secure\":true, \"cookie_domain\":\".labs.konghq.com\", \"cookie_samesite\":\"off\"}"
      KONG_PORTAL_EMAIL_VERIFICATION: "off"
      KONG_PORTAL_EMAILS_FROM: "kongtest@gmail.com"
      KONG_PORTAL_EMAILS_REPLY_TO: "kongtest@gmail.com"
      KONG_ADMIN_EMAILS_FROM: "kongtest@gmail.com"
      KONG_ADMIN_EMAILS_REPLY_TO: "kongtest@gmail.com"
      KONG_SMTP_MOCK: "off"
      KONG_SMTP_ADMIN_EMAILS: "kongtest@gmail.com"
      KONG_SMTP_HOST: "smtp"
      KONG_SMTP_PORT: 1025
     #KONG_SMTP_DOMAIN: ${KONG_SMTP_DOMAIN}
      KONG_NGINX_WORKER_PROCESSES: 1
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: "system"

  kong-dp:
    networks:
    - kong-edu-net
    image: kong/kong-gateway:3.1
    # image: kong/kong-gateway:2.8-alpine
    container_name: kong-dp
    hostname: kong-dp
    depends_on:
    - kong-cp
    volumes:
    - ${PWD}/ssl-certs:/srv/shared/ssl
    - ${PWD}/logs:/srv/shared/logs
    # - /Users/johnfitzpatrick/GitHub/kong-for-developers/gw-ops/installation/ssl-certs:/srv/shared/ssl
    # - /Users/johnfitzpatrick/GitHub/kong-for-developers/scratch:/srv/shared/logs
    # - /usr/local/kong/logs:/srv/shared/logs
    # - /home/ubuntu/kong-gateway-operations/installation/ssl-certs:/srv/shared/ssl
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    ports:
    - "8000:8000/tcp"
    - "8443:8443/tcp"
    - "8101:8101/tcp"
    environment:
      KONG_ROLE: "data_plane"
      KONG_CLUSTER_CERT: "/srv/shared/ssl/hybrid/cluster.crt"
      KONG_CLUSTER_CERT_KEY: "/srv/shared/ssl/hybrid/cluster.key"
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: "/srv/shared/ssl/hybrid/cluster.crt,system"
      KONG_CLUSTER_CONTROL_PLANE: "kong-cp:8005"
      KONG_CLUSTER_TELEMETRY_ENDPOINT: "kong-cp:8006"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 http2 ssl"
      KONG_STREAM_LISTEN: "0.0.0.0:5555, 0.0.0.0:5556 ssl reuseport backlog=65536"
      KONG_STATUS_LISTEN: "0.0.0.0:8101"
      KONG_PROXY_ACCESS_LOG: /srv/shared/logs/proxy_access.log
      KONG_PROXY_ERROR_LOG: /srv/shared/logs/proxy_error.log
      KONG_PROXY_STREAM_ACCESS_LOG: /srv/shared/logs/proxystream_access.log basic
      KONG_PROXY_STREAM_ERROR_LOG: /srv/shared/logs/proxystream_error.log
      KONG_DATABASE: "off"
      KONG_LICENSE_DATA: ${KONG_LICENSE_DATA}
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_VITALS: "on"
      KONG_VITALS_STRATEGY: prometheus
      KONG_VITALS_STATSD_ADDRESS: statsd:9125
      KONG_VITALS_TSDB_ADDRESS: prometheus:9090
      KONG_SSL_CERT_KEY: "/srv/shared/ssl/wildcard.key"
      KONG_SSL_CERT: "/srv/shared/ssl/wildcard.pem"
      KONG_NGINX_WORKER_PROCESSES: 1
      KONG_TRACING: "on"
      KONG_TRACING_WRITING_STRATEGY: "file"
      KONG_TRACING_TYPES: "all"
      KONG_TRACING_TIME_THRESHOLD: 0
      KONG_TRACING_WRITE_ENDPOINT: /srv/shared/logs/granular_tracing.log
      KONG_TRACING_DEBUG_HEADER: X-Trace

  smtp-server:
    networks:
    - kong-edu-net
    image: reachfive/fake-smtp-server:0.8.1
    container_name: smtp
    hostname: smtp
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 16s
      timeout: 16s
      retries: 16
    restart: on-failure
    ports:
    - "1080:1080/tcp"

  redis:
    networks:
    - kong-edu-net
    image: redis:alpine3.15
    container_name: redis
    hostname: redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    ports:
    - "6379:6379/tcp"

  prometheus:
    networks:
    - kong-edu-net
    image: prom/prometheus:v2.34.0
    container_name: prometheus
    hostname: prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml --log.level=debug
    healthcheck:
      test: ["CMD", "wget", "-S", "--spider", "http://prometheus:9090"]
      interval: 10s
      timeout: 15s
      retries: 10
    ports:
    - 9090:9090
    volumes:
    - ${PWD}/misc/prometheus.yaml:/etc/prometheus/prometheus.yaml

  statsd:
    networks:
    - kong-edu-net
    image: kong/statsd-exporter-advanced:0.3.1
    container_name: statsd
    hostname: statsd
    depends_on:
    - prometheus
    healthcheck:
      test: ["CMD", "wget", "-S", "--spider", "http://statsd:9102"]
      interval: 10s
      timeout: 15s
      retries: 10
    command: --statsd.mapping-config=/tmp/statsd.rules.yaml --statsd.listen-unixgram=''
    ports:
    - 9125:9125
    - 9102:9102
    volumes:
    - ${PWD}/misc/statsd.rules.yaml:/tmp/statsd.rules.yaml

  grafana:
    networks:
    - kong-edu-net
    image: grafana/grafana:8.4.6
    container_name: grafana
    hostname: grafana
    depends_on:
    - prometheus
    healthcheck:
      test: ["CMD", "wget", "-S", "--spider", "http://grafana:3000"]
      interval: 10s
      timeout: 15s
      retries: 10
    ports:
    - 3001:3000

  mockbin:
    networks:
    - kong-edu-net
    image: mashape/mockbin:latest
    container_name: mockbin
    hostname: mockbin.bankong
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    ports:
    - "80:8080/tcp"

  splunk:
    networks: 
    - kong-edu-net
    image: splunk/splunk:8.2
    hostname: splunk.bankong
    environment: 
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_PASSWORD: password
    ports:
      - "9001:8000"
      - "8089:8089"
      - "514:514/tcp"

  # datadog:
  #   networks: 
  #     - kong-edu-net
  #   build: datadog
  #   pid: host
  #   environment:
  #    - DD_API_KEY=${DD_API_KEY}
  #    - DD_SITE=datadoghq.com
  #   volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - /proc/:/host/proc/:ro
  #    - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

# BanKonG
  bankong-frontend:
   networks:
   - kong-edu-net
   image: svenwal/bankong-frontend:latest
   container_name: bankong-frontend
   hostname: frontend.bankong
   restart: on-failure
   ports:
    - 29080:8080
  bankong-backend-transactions:
   networks:
   - kong-edu-net
   image: svenwal/bankong-backend-transactions:latest
   container_name: bankong-backend-transactions
   hostname: backend-transactions.bankong
   restart: on-failure
   ports:
    - 3000:3000
   environment:
     BACKEND_REGION: your home
     BACKEND_DATACENTER: local laptop
     BACKEND_ARCHITECTURE: docker-compose
  bankong-backend-orders:
   networks:
   - kong-edu-net
   image: svenwal/bankong-backend-orders:latest
   container_name: bankong-backend-orders
   hostname: backend-orders.bankong
   restart: on-failure

  httpbin:
    container_name: httpbin
    hostname: httpbin.docker.local
    networks:
    - kong-edu-net
    image: kennethreitz/httpbin:latest
